import { NgModule } from '@angular/core';
import {
	MatButtonModule,
	MatFormFieldModule,
	MatInputModule,
	MatCheckboxModule,
	MatSelectModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatTableModule,
	MatProgressSpinnerModule,
	MatTooltipModule,
	MatTabsModule,
	MatMenuModule,
	MatAutocompleteModule,
	MatRadioModule,
	MatIconModule,
	MatProgressBarModule,
	MatCardModule,
	MatPaginatorModule,
	MatSortModule,
  MatSnackBarModule,
  MatToolbarModule,
  MatOptionModule
} from '@angular/material';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HeaderComponent } from './components/header/header.component';

@NgModule({
  declarations: [HeaderComponent],
  imports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatTabsModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatIconModule,
    MatProgressBarModule,
    MatCardModule,
    MatPaginatorModule,
    MatSortModule,
    MatSnackBarModule,
    MatToolbarModule,
		CommonModule,
		FormsModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    MatSelectModule,
    MatOptionModule,
    //BrowserAnimationsModule,
  ],
  exports: [
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatTabsModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatRadioModule,
    MatIconModule,
    MatProgressBarModule,
    MatCardModule,
    MatPaginatorModule,
    MatSortModule,
    MatSnackBarModule,
    MatToolbarModule,
		CommonModule,
		FormsModule,
    ReactiveFormsModule,
    HeaderComponent,
    MatFormFieldModule,
    MatSelectModule,
    MatOptionModule,
    HeaderComponent,
  ]
})
export class SharedModule {}
